routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|-------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('admin.dashboard');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('all-product', 'Buyer\ProductController@view')->name('product.all');
Route::resource('product', 'Buyer\ProductController');
Route::get('Procurement-view', 'Buyer\ProcurementrequestController@view')->name('procurement.all');
Route::get('procurement/product/{val}', 'Buyer\ProcurementrequestController@getProduct');
Route::get('procurements/all', 'Buyer\ProcurementrequestController@procurements')->name('procurements.show');

Route::get('procurements/send/{id}', 'Buyer\ProcurementrequestController@sendReq')->name('send.req');
Route::get('procurements/bid', 'Buyer\ProcurementrequestController@getBid')->name('procurements.bid');

Route::get('procurement/accept/{id}', 'Buyer\ProcurementrequestController@accept')->name('procurement.accept');
Route::resource('procurement', 'Buyer\ProcurementrequestController');


Route::post('bid/{id}', 'Supplier\SupplierController@bid')->name('supplier.bid');
Route::resource('supplier', 'Supplier\SupplierController');

app/Http/Controllers/Buyer/SupplierController.php
<?php

namespace App\Http\Controllers\Buyer;

use App\Buyer\Supplier;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Supplier::all();
    }

    public function view()
    {
        return view('admin.pages.supplier');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
        'name'=>'required',
        'email'=>'required',
        'address'=>'required',
        ]);

        $supplier = new Supplier;
        $supplier->name = $request->name;
        $supplier->email = $request->email;
        $supplier->address = $request->address;
        $supplier->save();
        return "Perfect";
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'email'=>'required',
            'address'=>'required',
            ]);
    
            $supplier = Supplier::find($id);
            $supplier->name = $request->name;
            $supplier->email = $request->email;
            $supplier->address = $request->address;
            $supplier->save();
            return "update perfect";
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier = Supplier::find($id);
        $supplier->delete();
        return "delete successfully";
    }
}

app/Http/Controllers/Supplier/SupplierController.php
<?php

namespace App\Http\Controllers\Supplier;

use App\Bid;
use App\User;
use App\Buyer\Product;
use App\Buyer\Procurement;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $procurements = Procurement::where('req_send',1)->get();
        $data['procurements'] = Auth::user()->Procurements;
        $data['bid'] = null;
        $data['approved'] = Auth::user()->Bids;



        // $bided = Auth::user()->Procurements;
        // $bided = User::with(['Procurements' => function ($q) {
        //     $q->where('user_id', Auth::user()->id)->select('bided')->where('bided', 1);
        // }])->first();

        // $bided = Auth::user()->procurements();
        // dd($bided);
        // $bided = Procurement::all()->Suppliers->where('user_id', Auth::user()->id)->get();


        // foreach ($bided->Procurements as $key => $value) {
        //     # code...
        // }

        return view('supplier.pages.buyerRequest', $data);
    }

    public function bid(Request $request, $id)
    {



        $request->validate([
            'product_id' => 'required',
            'qty' =>  'required',
            'unit_price' =>  'required',
            'total' =>  'required',


        ]);

        Bid::create([
            'user_id' => $request->supplier_id,
            'product_id' => $request->product_id,
            'procurement_id' => $id,
            'qty' => $request->qty,
            'unit_price' => $request->unit_price,
            'total' => $request->total,
            'details' => $request->details,


        ]);
        // Auth::user()->Procurements()->sync('bided', 1);
        // Auth::user()->Procurements()->where('product_id', $request->product_id)->update(['bided' => 1]);
        // Auth::user()->Procurements()->sync(['bided' => 1]);
        Auth::user()->procurements()->updateExistingPivot(
            $id,
            ['bided' => 1]
        );
        return redirect()->route('supplier.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['procurements'] = Auth::user()->Procurements->where('req_send', 1);
        $data['bid'] = Procurement::find($id);
        $data['approved'] = Auth::user()->Bids->where('bid_approval', 1);
        $data['procurement_id'] = $id;
        return view('supplier.pages.buyerRequest', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/supplier/pages/buyerRequest.blade.php
@extends('home')

@section('content')
<div class="content-wrapper" id="app">
    <div class="row mt-5">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Procurement Requests</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>serial</th>
                  <th>Suppliers</th>
                  <th>Product Name</th>
                  <th>Qty</th>
                  <th>Unit Price</th>
                  <th>Details</th>
                  <th>Total Price</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                  {{-- {{dd($procurements)}} --}}
                 
                  @foreach ($procurements as $key => $request)
                  <tr>
                  <td>{{$key+1}}</td>
                      <td> 
                        {{Auth::user()->name}}
                      </td>
                      <td>
                        {{$request->Product->name}}
                      </td>

                      <td>{{$request->qty}}</td>
                      <td>{{$request->unitPrice}}</td>
                      <td>{{$request->details}}</td>
                      <td>{{$request->total}}</td>
                      <td>
                        {{-- {{dd($request->pivot->bided)}} --}}
{{-- 
                        @if ($request->pivot->bided == 1)
                           
                        <a href="{{route('supplier.show',$request->id)}}" class="btn btn-success disabled float-left mr-2 ">Bided</a>

                        @else 
                        <a href="{{route('supplier.show',$request->id)}}" class="btn btn-success float-left mr-2 ">Bid</a>
                        @endif --}}
                         

                        {{-- {{ dd($request->pivot) }} --}}
                         

                          @if ($request->pivot->bided == 1 && $request->pivot->is_approved == 0)

                            <a href="{{route('supplier.show',$request->id)}}" class="btn btn-success disabled float-left mr-2 ">Bided</a>
                          @elseif($request->pivot->is_approved == 1 && $request->pivot->bided == 1)
                             
                              <a href="{{route('supplier.show',$request->id)}}" class="btn btn-success float-left mr-2 disabled">Approved</a>
                           @else
                           <a href="{{route('supplier.show',$request->id)}}" class="btn btn-success float-left mr-2 ">Bid</a>
                          @endif
                            
                            

                          
{{--                              
                          @if ($request->pivot->bided == 1)
                              
                                 
                               @if (count($approved) != 0)
                                  @foreach ($approved as $approve)
                                    @if (($approve->bid_approval == 1))
                                        <a href="{{route('supplier.show',$request->id)}}" class="btn btn-success float-left mr-2 disabled">Approved</a>

                                        @else  

                                        <a href="{{route('supplier.show',$request->id)}}" class="btn btn-success disabled float-left mr-2 ">Bided</a>
                                    @endif

                                  @endforeach
                              
                               

                              
                              
                               @endif  
                               
                            
                          @endif

                         @if ($request->pivot->bided == 0)
                         <a href="{{route('supplier.show',$request->id)}}" class="btn btn-success float-left mr-2 ">Bid</a>
                         @endif
                       --}}
                        
 
                   
                     
                           

                       
                    </td>
                  </tr>


                
              @endforeach 
                  
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
        </div>


       
        @if ($bid != null)
 

        <div class="col-8">
          <form role="form" action="{{route('supplier.bid', $procurement_id)}}" method="POST" id="form">
            @csrf
          <div class="card-body">
            <div class="form-group">
              <label for="exampleInputEmail1">Supplier Name</label>
              <input  value="{{Auth::user()->id}}" name="supplier_id" hidden>
              <input type="text" class="form-control" id="exampleInputEmail1" value="{{Auth::user()->name}}" readonly>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Product</label>
              <input value="{{$bid->Product->id}}" name="product_id" hidden>
              <input type="text" class="form-control" id="exampleInputEmail1" value="{{$bid->Product->name}}" readonly>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Quantity</label>
              <input type="text" class="form-control" id="exampleInputEmail1" value="{{$bid->qty}}" name="qty" readonly>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Unit Price</label>
              <input type="text" class="form-control" id="exampleInputEmail1" value="{{$bid->unitPrice}}" name="unit_price">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Total Price</label>
              <input type="text" class="form-control" id="exampleInputEmail1" value="{{$bid->total}}" name="total">
            </div>
            <div class="form-group">
              <label for="">Details</label>
              <textarea class="form-control details" name="details" id="" rows="3"> </textarea>
            </div>
          </div>
          <!-- /.card-body -->

          <div class="card-footer">
          <button type="submit" class="btn btn-primary save-data {{$bid->bid_approval == true ? "disabled" : ""}}" >{{$bid->bid_approval == true ? "Approved" : "Bid Now"}}</button>
          </div>
        </form>
        </div>
        @endif

    </div>
</div>
@endsection
@push('js')
    {{-- <script>
    
  $(".save-data").click(function(event){
      event.preventDefault();

      let supplier_id = $("input[name=supplier_id]").val();
      let product_id = $("input[name=product_id]").val();
      let qty = $("input[name=qty]").val();
      let unitPrice = $("input[name=unit_price]").val();
      let total = $("input[name=total]").val();
      let details = $(".details").val();
      let _token   = $('meta[name="csrf-token"]').attr('content');
      let url = window.location.origin;

      console.log(this.form);
      $.ajax({
        url: url+"/bid",
        type:"POST",
        data:{
          supplier_id:supplier_id,
          product_id:product_id,
          qty:qty,
          unitPrice:unitPrice,
          total:total,
          details:details,
          _token: _token
        },
        cache:false,
        success:function(response){
          console.log(response);
          $("#form").trigger("reset");
        },
       });
       
  });
    </script> --}}
@endpush